# Generated by Django 4.2.11 on 2024-09-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pro_alter_products_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pro',
        ),
    ]
