# Generated by Django 4.2.11 on 2024-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='display_size',
            field=models.CharField(choices=[('12', 'Small (12 inch)'), ('14', 'Medium (14 inch)'), ('15.6', 'Large (15.6 inch)')], default='14', help_text='Select the laptop display size', max_length=10),
        ),
    ]
